name: Deploy Next.js site to gh-pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          generator_config_file: next.config.mjs
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-
      - name: Install dependencies
        run: bun install
      - name: Build with Next.js
        run: bunx next build
      - name: Move out directory
        run: mv out /tmp/out
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Preserve pr-preview directories and clear other files
        run: |
          mkdir -p /tmp/pr-previews
          find . -maxdepth 1 -type d -name 'pr-preview-*' -exec mv {} /tmp/pr-previews/ \;
          git rm -rf .
          git clean -fxd
          mv /tmp/pr-previews/* .
      - name: Copy new build
        run: |
          cp -r /tmp/out/* .
          touch .nojekyll
      - name: Commit changes to gh-pages branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add .
          git diff --staged --quiet || git commit -m "Deploy to gh-pages: ${{ github.sha }}"
          git push origin gh-pages
